---
- name: настройка серверов
  hosts: all
  become: yes

  tasks:
    - name: Установить зависимости
      apt:
        name:
          - curl
          - software-properties-common
          - ca-certificates
          - apt-transport-https
        state: present
        update_cache: yes

    - name: Добавить GPG-ключ Docker
      shell: wget -O- https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor | tee /etc/apt/keyrings/docker.gpg > /dev/null
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Добавить Docker-репозиторий
      shell: echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Обновить кеш пакетов
      apt:
        update_cache: yes

    - name: Установить Docker CE
      apt:
        name: docker-ce
        state: present

    - name: установка Git
      apt:
        name: git
        state: present

    - name: установка Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: скачивание скрипта GitLab Runner
      shell: curl -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh | bash
      become: yes

    - name: установка GitLab Runner
      apt:
        name: gitlab-runner
        state: present
