name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t symbion12/ytest-repo:latest .
          docker tag symbion12/ytest-repo:latest symbion12/ytest-repo:${{ github.sha }}

      - name: Push Docker Image
        run: |
          docker push symbion12/ytest-repo:latest
          docker push symbion12/ytest-repo:${{ github.sha }}    

    
