name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: dimonsymbion
          password: dckr_pat_UW72LLkx0KjwY1xceA_d3qBq17g

      - name: Build Docker image
        run: |
          docker build -t dimonsymbion/devops:$GITHUB_SHA .

      - name: Push Docker image
        run: |
          docker push dimonsymbion/devops:$GITHUB_SHA
    
