name: Build and Deploy Docker Image

on:
#  push:
#   tags:
#      - 'v*'  # Это будет запускаться только при пуше тегов вида v1.0.0, v2.0.0 и т. д.
#pull_request:
#    branches:
#      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Твои DockerHub username
          password: ${{ secrets.DOCKER_PASSWORD }}  # Твои DockerHub password

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        run: |
          IMAGE_NAME="dimonsymbion/devops:${GITHUB_REF##*/}"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to Kubernetes
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.K8S_SERVER }}  # IP твоего сервера
          username: ${{ secrets.K8S_USERNAME }}  # Пользователь для SSH
          key: ${{ secrets.K8S_PRIVATE_KEY }}  # Твой приватный ключ для подключения к серверу
          script: |
            kubectl config set-cluster kubernetes --server=https//:10.10.0.3:6443
            kubectl config set-credentials my-user --token=$K8S_TOKEN
            kubectl config set-context my-context --cluster=kubernetes --user=kubernetes-admin@kubernetes
            kubectl config use-context my-context
            helm upgrade --install diplom ./chart --set image.tag=${GITHUB_REF#refs/tags/}
