name: CI/CD Pipeline
on:
  push:
    tags:
      - 'v*' 
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          TAG=$(git describe --tags --always)
          docker build -t docker.io/dimonsymbion/devops:$TAG .
          docker push docker.io/dimonsymbion/devops:$TAG
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }} 
      - name: Check Kubernetes Cluster
        run: kubectl cluster-info
          

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy to Kubernetes
        run: |
          TAG=$(git describe --tags --always)
          helm upgrade --install my-app ./diplom --set image.tag=$TAG
          kubectl rollout status deployment/my-app
