apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  selector:
    app: {{ .Release.Name }}-db
  ports:
    - protocol: TCP
      port: {{ .Values.postgres.port }}
      targetPort: 5432
  type: ClusterIP
